module Rakuda
  module Models
    class Page < Data
      def self.new: (
        title: String,
        url: String,
        body: String,
        date: (Time | nil),
        summary: String,
        has_more: bool,
        content: nil
      ) -> Page

      def initialize: (
        title: String,
        url: String,
        body: String,
        date: (Time | nil),
        summary: String,
        has_more: bool,
        content: nil
      ) -> void

      def title: () -> String
      def url: () -> String
      def body: () -> String
      def date: () -> (Time | nil)
      def summary: () -> String
      def has_more: () -> bool
      def content: () -> nil
    end
  end
end
