module Rakuda
  module Models
    class Post < Data
      def self.new: (
        title: String,
        slug: String,
        date: Time,
        categories: Array[untyped],
        draft: bool,
        body: String,
        url: String,
        summary: String,
        has_more: bool
      ) -> Post

      def initialize: (
        title: String,
        slug: String,
        date: Time,
        categories: Array[untyped],
        draft: bool,
        body: String,
        url: String,
        summary: String,
        has_more: bool
      ) -> void

      def title: () -> String
      def slug: () -> String
      def date: () -> Time
      def categories: () -> Array[untyped]
      def draft: () -> bool
      def body: () -> String
      def url: () -> String
      def summary: () -> String
      def has_more: () -> bool
    end
  end
end
