module Rakuda
  class CLI
    type options = { source: String, destination: String, port: Integer }

    def self.run: (Array[String] argv) -> void
    def self.usage: () -> String

    private

    def self.build: (options options) -> void
    def self.serve: (options options) -> void
  end
end
