module Rakuda
  module MarkdownRenderer
    SKIP_TAGS: Array[String]

    def self.render: (String markdown, ?autolink: bool) -> String

    private

    def self.html_for: (String markdown) -> String
  end
end
