module Rakuda
  class PageLoader
    @source_dir: String

    def self.load: (String source_dir) -> Array[Models::Page]
    def initialize: (String source_dir) -> void
    def load: () -> Array[Models::Page]

    private

    def build: (String path) -> Models::Page
  end
end
