module Rakuda
  module Server
    EMPTY_HEADERS: Hash[String, String]
    EMPTY_BODY: Array[untyped]

    def self.app: (String root) -> Rack::Static
    def self.start: (root: String, ?port: Integer) -> void
  end
end
