module Rakuda
  class TemplateRenderer
    @layouts_dir: String

    def initialize: (String layouts_dir) -> void
    def render: (String template_name, Hash[Symbol, untyped] assigns) -> String

    class AssignContext
      @assigns: Hash[Symbol, untyped]
      @renderer: TemplateRenderer

      def initialize: (Hash[Symbol, untyped] assigns, TemplateRenderer renderer) -> void
      def render_partial: (String name, ?Hash[Symbol, untyped] extra) -> String
      def get_binding: () -> Binding
    end
  end
end
