module Rakuda
  class UrlGenerator
    @pattern: String

    def initialize: (String permalink_pattern) -> void
    def post_url: ((Date | Time) date, String slug) -> String
    def home_page_url: (Integer page_num) -> ("/" | String)
  end
end
