module Rakuda
  module Generators
    class Section
      @config: Config
      @posts: Array[Models::Post]
      @renderer: TemplateRenderer
      @markdown: markdown
      @site: SiteContext::site_hash

      def initialize: (
        config: Config,
        posts: Array[Models::Post],
        renderer: TemplateRenderer,
        markdown: markdown
      ) -> void

      def generate: () -> Array[generated_page]

      private

      def post_to_list_hash: (Models::Post post) -> Hash[Symbol, untyped]
    end
  end
end
